<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Kelola_tindaklanjut extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        is_login();
        $this->load->model('Model_tindaklanjut');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->template->load('template','kelola_tindaklanjut/tbl_ppa_tindaklanjut_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Model_tindaklanjut->json();
    }

    public function read($id) 
    {
        $row = $this->Model_tindaklanjut->get_by_id($id);
        if ($row) {
            $data = array(
	    );
            $this->template->load('template','kelola_tindaklanjut/tbl_ppa_tindaklanjut_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('kelola_tindaklanjut'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('kelola_tindaklanjut/create_action'),
	);
        $this->template->load('template','kelola_tindaklanjut/tbl_ppa_tindaklanjut_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
	    );

            $this->Model_tindaklanjut->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success 2');
            redirect(site_url('kelola_tindaklanjut'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Model_tindaklanjut->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('kelola_tindaklanjut/update_action'),
	    );
            $this->template->load('template','kelola_tindaklanjut/tbl_ppa_tindaklanjut_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('kelola_tindaklanjut'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('', TRUE));
        } else {
            $data = array(
	    );

            $this->Model_tindaklanjut->update($this->input->post('', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('kelola_tindaklanjut'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Model_tindaklanjut->get_by_id($id);

        if ($row) {
            $this->Model_tindaklanjut->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('kelola_tindaklanjut'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('kelola_tindaklanjut'));
        }
    }

    public function _rules() 
    {

	$this->form_validation->set_rules('', '', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

    public function excel()
    {
        $this->load->helper('exportexcel');
        $namaFile = "tbl_ppa_tindaklanjut.xls";
        $judul = "tbl_ppa_tindaklanjut";
        $tablehead = 0;
        $tablebody = 1;
        $nourut = 1;
        //penulisan header
        header("Pragma: public");
        header("Expires: 0");
        header("Cache-Control: must-revalidate, post-check=0,pre-check=0");
        header("Content-Type: application/force-download");
        header("Content-Type: application/octet-stream");
        header("Content-Type: application/download");
        header("Content-Disposition: attachment;filename=" . $namaFile . "");
        header("Content-Transfer-Encoding: binary ");

        xlsBOF();

        $kolomhead = 0;
        xlsWriteLabel($tablehead, $kolomhead++, "No");

	foreach ($this->Model_tindaklanjut->get_all() as $data) {
            $kolombody = 0;

            //ubah xlsWriteLabel menjadi xlsWriteNumber untuk kolom numeric
            xlsWriteNumber($tablebody, $kolombody++, $nourut);

	    $tablebody++;
            $nourut++;
        }

        xlsEOF();
        exit();
    }

}

/* End of file Kelola_tindaklanjut.php */
/* Location: ./application/controllers/Kelola_tindaklanjut.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-03-07 03:23:28 */
/* http://harviacode.com */