<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Model_kelola_kak extends CI_Model
{

    public $table = 'tb_kak';
    public $id = 'Id_kak';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('Id_kak', $q);
	$this->db->or_like('Kode_skpd', $q);
	$this->db->or_like('Wawasan', $q);
	$this->db->or_like('Faktor_Kesenjangan', $q);
	$this->db->or_like('Sebab_Kesenjagan_Internal', $q);
	$this->db->or_like('Sebab_Kesenjagan_Eksternal', $q);
	$this->db->or_like('Reformasi_Tujuan', $q);
	$this->db->or_like('Rencana_Aksi', $q);
	$this->db->or_like('Data_Dasar', $q);
	$this->db->or_like('Tahun_Anggaran', $q);
	$this->db->or_like('Kode_Program', $q);
	$this->db->or_like('Sasaran_Program', $q);
	$this->db->or_like('Program', $q);
	$this->db->or_like('Kegiatan', $q);
	$this->db->or_like('Sub_Kegiatan', $q);
	$this->db->or_like('Uraian_Kegiatan', $q);
	$this->db->or_like('Tujuan', $q);
	$this->db->or_like('Maksud', $q);
	$this->db->or_like('Dasar_Hukum', $q);
	$this->db->or_like('Gambaran_Umum', $q);
	$this->db->or_like('Cara_Pelaksanan', $q);
	$this->db->or_like('Tempat_Pelaksaan', $q);
	$this->db->or_like('Pelaksana_Penaggungjawab', $q);
	$this->db->or_like('Analisis_Situasi', $q);
	$this->db->or_like('Jadwal', $q);
	$this->db->or_like('Biaya', $q);
	$this->db->or_like('Indikator_Kinerja', $q);
	$this->db->or_like('Batasan_Kegiatan', $q);
	$this->db->or_like('Hasil', $q);
	$this->db->or_like('Belanja1_Tujuan', $q);
	$this->db->or_like('Belanja1_Alokasianggaran', $q);
	$this->db->or_like('Belanja2_Tujuan', $q);
	$this->db->or_like('Belanja2_Alokasianggaran', $q);
	$this->db->or_like('Capaian_Program', $q);
	$this->db->or_like('update_at', $q);
	$this->db->or_like('create_at', $q);
	$this->db->or_like('delete_at', $q);
	$this->db->or_like('user_id', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('Id_kak', $q);
	$this->db->or_like('Kode_skpd', $q);
	$this->db->or_like('Wawasan', $q);
	$this->db->or_like('Faktor_Kesenjangan', $q);
	$this->db->or_like('Sebab_Kesenjagan_Internal', $q);
	$this->db->or_like('Sebab_Kesenjagan_Eksternal', $q);
	$this->db->or_like('Reformasi_Tujuan', $q);
	$this->db->or_like('Rencana_Aksi', $q);
	$this->db->or_like('Data_Dasar', $q);
	$this->db->or_like('Tahun_Anggaran', $q);
	$this->db->or_like('Kode_Program', $q);
	$this->db->or_like('Sasaran_Program', $q);
	$this->db->or_like('Program', $q);
	$this->db->or_like('Kegiatan', $q);
	$this->db->or_like('Sub_Kegiatan', $q);
	$this->db->or_like('Uraian_Kegiatan', $q);
	$this->db->or_like('Tujuan', $q);
	$this->db->or_like('Maksud', $q);
	$this->db->or_like('Dasar_Hukum', $q);
	$this->db->or_like('Gambaran_Umum', $q);
	$this->db->or_like('Cara_Pelaksanan', $q);
	$this->db->or_like('Tempat_Pelaksaan', $q);
	$this->db->or_like('Pelaksana_Penaggungjawab', $q);
	$this->db->or_like('Analisis_Situasi', $q);
	$this->db->or_like('Jadwal', $q);
	$this->db->or_like('Biaya', $q);
	$this->db->or_like('Indikator_Kinerja', $q);
	$this->db->or_like('Batasan_Kegiatan', $q);
	$this->db->or_like('Hasil', $q);
	$this->db->or_like('Belanja1_Tujuan', $q);
	$this->db->or_like('Belanja1_Alokasianggaran', $q);
	$this->db->or_like('Belanja2_Tujuan', $q);
	$this->db->or_like('Belanja2_Alokasianggaran', $q);
	$this->db->or_like('Capaian_Program', $q);
	$this->db->or_like('update_at', $q);
	$this->db->or_like('create_at', $q);
	$this->db->or_like('delete_at', $q);
	$this->db->or_like('user_id', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Model_kelola_kak.php */
/* Location: ./application/models/Model_kelola_kak.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-07-01 04:04:41 */
/* http://harviacode.com */