<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Model_department extends CI_Model
{

    public $table = 'ref_department';
    public $id = 'id_department';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_department,name,leader,nip_leader,jabatan,pangkat,address,phone,email,image,website,views,status,type,created_id,created_date,update_id,update_date');
        $this->datatables->from('ref_department');
        
         if ($_SESSION['id_user_level'] == 2) {
        $this->datatables->where('ref_department.id_department', $_SESSION['id_skpd']);
        }
        //add this line for join
        //$this->datatables->join('table2', 'ref_department.field = table2.field');
        
         if ($_SESSION['id_user_level'] == 2) {
        $this->datatables->add_column('action', anchor(site_url('master_department/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
            ".anchor(site_url('master_department/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
               ", 'id_department');
        return $this->datatables->generate();
         }else
         {
        $this->datatables->add_column('action', anchor(site_url('master_department/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
            ".anchor(site_url('master_department/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
               ".anchor(site_url('master_department/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_department');
        return $this->datatables->generate();
         }
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_department', $q);
	$this->db->or_like('name', $q);
	$this->db->or_like('leader', $q);
	$this->db->or_like('nip_leader', $q);
	$this->db->or_like('jabatan', $q);
	$this->db->or_like('address', $q);
	$this->db->or_like('phone', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('image', $q);
	$this->db->or_like('website', $q);
	$this->db->or_like('views', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('type', $q);
	$this->db->or_like('created_id', $q);
	$this->db->or_like('created_date', $q);
	$this->db->or_like('update_id', $q);
	$this->db->or_like('update_date', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_department', $q);
	$this->db->or_like('name', $q);
	$this->db->or_like('leader', $q);
	$this->db->or_like('nip_leader', $q);
	$this->db->or_like('jabatan', $q);
	$this->db->or_like('address', $q);
	$this->db->or_like('phone', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('image', $q);
	$this->db->or_like('website', $q);
	$this->db->or_like('views', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('type', $q);
	$this->db->or_like('created_id', $q);
	$this->db->or_like('created_date', $q);
	$this->db->or_like('update_id', $q);
	$this->db->or_like('update_date', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Model_department.php */
/* Location: ./application/models/Model_department.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-08-01 17:31:21 */
/* http://harviacode.com */