<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Model_tor extends CI_Model
{

    public $table = 'tb_tor';
    public $id = 'tor_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('ref_department.name,tor_skpd,tor_program,tor_sasaran,tor_kegiatan,tor_id,tor_kak_id,tor_dasar_hukum,tor_gambaran_umum,tor_uraian_kerja,tor_indikator_kerja,tor_batasan_kegiatan,tor_maksud_tujuan,tor_cara_pelaksanaan,tor_tempat_pelaksanaan,tor_biaya');
        $this->datatables->from('tb_tor');
        //add this line for join
        
      $this->datatables->join('ref_department', 'ref_department.id_department=tb_tor.tor_skpd', 'left');
      
         if ($_SESSION['id_user_level'] == 2) {
        $this->datatables->where('tb_tor.tor_skpd', $_SESSION['id_skpd']);
        }
        $this->datatables->add_column('action', anchor(site_url('kelola_tor/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
            ".anchor(site_url('kelola_tor/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
                ".anchor(site_url('kelola_tor/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'tor_id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
//        $this->db->where($this->id, $id);
//        return $this->db->get($this->table)->row();
        
           $this->db->select('*');
           
        $this->db->join('ref_department', 'ref_department.id_department=tb_tor.tor_skpd', 'left');
        $this->db->where($this->table . '.tor_id', $id);
          return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('tor_id', $q);
	$this->db->or_like('tor_kak_id', $q);
	$this->db->or_like('tor_dasar_hukum', $q);
	$this->db->or_like('tor_gambaran_umum', $q);
	$this->db->or_like('tor_uraian_kerja', $q);
	$this->db->or_like('tor_indikator_kerja', $q);
	$this->db->or_like('tor_batasan_kegiatan', $q);
	$this->db->or_like('tor_maksud_tujuan', $q);
	$this->db->or_like('tor_cara_pelaksanaan', $q);
	$this->db->or_like('tor_tempat_pelaksanaan', $q);
	$this->db->or_like('tor_penanggung_jawab', $q);
	$this->db->or_like('tor_jadwal', $q);
	$this->db->or_like('tor_biaya', $q);
	$this->db->or_like('create_id', $q);
	$this->db->or_like('update_id', $q);
	$this->db->or_like('create', $q);
	$this->db->or_like('update', $q);
	$this->db->or_like('delete', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('tor_id', $q);
	$this->db->or_like('tor_kak_id', $q);
	$this->db->or_like('tor_dasar_hukum', $q);
	$this->db->or_like('tor_gambaran_umum', $q);
	$this->db->or_like('tor_uraian_kerja', $q);
	$this->db->or_like('tor_indikator_kerja', $q);
	$this->db->or_like('tor_batasan_kegiatan', $q);
	$this->db->or_like('tor_maksud_tujuan', $q);
	$this->db->or_like('tor_cara_pelaksanaan', $q);
	$this->db->or_like('tor_tempat_pelaksanaan', $q);
	$this->db->or_like('tor_penanggung_jawab', $q);
	$this->db->or_like('tor_jadwal', $q);
	$this->db->or_like('tor_biaya', $q);
	$this->db->or_like('create_id', $q);
	$this->db->or_like('update_id', $q);
	$this->db->or_like('create', $q);
	$this->db->or_like('update', $q);
	$this->db->or_like('delete', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Model_tor.php */
/* Location: ./application/models/Model_tor.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-07-31 15:50:09 */
/* http://harviacode.com */