<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Model_kak extends CI_Model
{

    public $table = 'tb_kak';
    public $id = 'Id_kak';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    //model
	  function search_program($title){
 
        $this->db->like('nama_program', $title , 'both');
        $this->db->order_by('nama_program', 'ASC');
        $this->db->limit(20);
        return $this->db->get('ref_program')->result();
    }

    function search_giat($title){
 
        $this->db->like('nama_giat', $title , 'both');
        $this->db->order_by('nama_giat', 'ASC');
        $this->db->limit(20);
        return $this->db->get('ref_program')->result();
    }

    // datatables
    function json() {
        $this->datatables->select('ref_department.name,Id_kak,Kode_skpd,Tahun_Anggaran,Kode_Program,Program,Kegiatan,Sub_Kegiatan,Tujuan,Analisis_Situasi,Hasil,Belanja1_Tujuan,Belanja1_Alokasianggaran,Belanja2_Tujuan,Belanja2_Alokasianggaran,Capaian_Program');
      //  $this->datatables->from('tb_kak');
        $this->datatables->from('tb_kak');

        $this->datatables->join('ref_department', 'ref_department.id_department=tb_kak.Kode_skpd', 'left');

        if ($_SESSION['id_user_level'] == 2) {
          $this->datatables->where('tb_kak.kode_skpd', $_SESSION['id_skpd']);
      }
        //add this line for join
        //$this->datatables->join('table2', 'tb_kak.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('data_kak/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
            ".anchor(site_url('data_kak/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
            ".anchor(site_url('data_kak/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'Id_kak');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('Id_kak', $q);
	$this->db->or_like('Kode_skpd', $q);
	$this->db->or_like('Tahun_Anggaran', $q);
	$this->db->or_like('Kode_Program', $q);
	$this->db->or_like('Program', $q);
	$this->db->or_like('Kegiatan', $q);
	$this->db->or_like('Sub_Kegiatan', $q);
	$this->db->or_like('Tujuan', $q);
	$this->db->or_like('Analisis_Situasi', $q);
	$this->db->or_like('Hasil', $q);
	$this->db->or_like('Belanja1_Tujuan', $q);
	$this->db->or_like('Belanja1_Alokasianggaran', $q);
	$this->db->or_like('Belanja2_Tujuan', $q);
	$this->db->or_like('Belanja2_Alokasianggaran', $q);
	$this->db->or_like('Capaian_Program', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('Id_kak', $q);
	$this->db->or_like('Kode_skpd', $q);
	$this->db->or_like('Tahun_Anggaran', $q);
	$this->db->or_like('Kode_Program', $q);
	$this->db->or_like('Program', $q);
	$this->db->or_like('Kegiatan', $q);
	$this->db->or_like('Sub_Kegiatan', $q);
	$this->db->or_like('Tujuan', $q);
	$this->db->or_like('Analisis_Situasi', $q);
	$this->db->or_like('Hasil', $q);
	$this->db->or_like('Belanja1_Tujuan', $q);
	$this->db->or_like('Belanja1_Alokasianggaran', $q);
	$this->db->or_like('Belanja2_Tujuan', $q);
	$this->db->or_like('Belanja2_Alokasianggaran', $q);
	$this->db->or_like('Capaian_Program', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
       
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Model_kak.php */
/* Location: ./application/models/Model_kak.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-04-13 09:18:16 */
/* http://harviacode.com */