<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Model_relaas extends CI_Model
{

    public $table = 'tbl_relaas';
    public $id = 'id_relaas';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('ref_pengadilan.nama_pengadilan,id_relaas,nama_pihak,ref_jenis_pihak.jenis_pihak,pengadilan,no_perkara,keterangan,tanggal_hadir_sidang,tgl_pengumuman,tgl_pemberitahuan_putusan,berkas,status_persidangan,user_id,create_at,update_at,delete_at');
        $this->datatables->from('tbl_relaas');
        
        $this->datatables->join('ref_jenis_pihak', 'tbl_relaas.jenis_pihak = ref_jenis_pihak.id_jenis','left');
        $this->datatables->join('ref_pengadilan', 'tbl_relaas.pengadilan = ref_pengadilan.id_pengadilan','left');
        $this->datatables->where('tbl_relaas.delete_at is  NULL', NULL, FALSE);
        //add this line for join
       
        $this->datatables->add_column('action', anchor(site_url('kelola_relaas/read/$1'), '<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm')) . " 
            " . anchor(site_url('kelola_relaas/update/$1'), '<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm')) . " 
                " . anchor(site_url('kelola_relaas/delete/$1'), '<i class="fa fa-trash-o" aria-hidden="true"></i>', 'class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_relaas');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        $this->db->join('ref_pengadilan', 'tbl_relaas.pengadilan = ref_pengadilan.id_pengadilan','left');
        $this->db->join('ref_jenis_pihak', 'ref_jenis_pihak.id_jenis = tbl_relaas.jenis_pihak','left');
      
        
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_relaas', $q);
	$this->db->or_like('nama_pihak', $q);
	$this->db->or_like('jenis_pihak', $q);
	$this->db->or_like('pengadilan', $q);
	$this->db->or_like('no_perkara', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->or_like('tanggal_hadir_sidang', $q);
	$this->db->or_like('tgl_pengumuman', $q);
	$this->db->or_like('tgl_pemberitahuan_putusan', $q);
	$this->db->or_like('berkas', $q);
	$this->db->or_like('status_persidangan', $q);
	$this->db->or_like('user_id', $q);
	$this->db->or_like('create_at', $q);
	$this->db->or_like('update_at', $q);
	$this->db->or_like('delete_at', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_relaas', $q);
	$this->db->or_like('nama_pihak', $q);
	$this->db->or_like('jenis_pihak', $q);
	$this->db->or_like('pengadilan', $q);
	$this->db->or_like('no_perkara', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->or_like('tanggal_hadir_sidang', $q);
	$this->db->or_like('tgl_pengumuman', $q);
	$this->db->or_like('tgl_pemberitahuan_putusan', $q);
	$this->db->or_like('berkas', $q);
	$this->db->or_like('status_persidangan', $q);
	$this->db->or_like('user_id', $q);
	$this->db->or_like('create_at', $q);
	$this->db->or_like('update_at', $q);
	$this->db->or_like('delete_at', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Model_relaas.php */
/* Location: ./application/models/Model_relaas.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-10-18 04:48:15 */
/* http://harviacode.com */