<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Model_welcome extends CI_Model
{

    public $table = 'rencana_aksi';
    public $id = 'id';
    public $order = 'DESC';
  

    function __construct()
    {
        parent::__construct();
    }
    
     function json_berita() {
         
         
        $this->datatables->select('berita_acara_id,berita_acara_status,berita_acara_dihentikan,berita_acara_kode,berita_acara_tgl,berita_acara_hari,berita_acara_kronologi,berita_acara_penerima_laporan,berita_acara_kepala_uptd,pelapor_nama,pelapor_tgl,pelapor_tempat,pelapor_idusers,pelapor_nik,pelapor_pekerjaan,pelapor_telepon,pelapor_kab,pelapor_kec,pelapor_desa,korban_nik,korban_nama,korban_jeniskelamin,korban_agama,korban_tempat,korban_tgl_lahir,korban_prop,korban_kab,korban_kec,korban_desa,korban_foto1,korban_foto2,korban_email,korban_telepon,korban_tglkejadian,pelaku_nama,pelaku_jenis_kelamin,pelaku_usia,pelaku_hubungan,pelaku_pendidikan,pelaku_alamat,pelaku_prop,pelaku_kab,pelaku_kec,pelaku_desa,pelaku_nik,lapor_anonim,lapor_rahasia,lapor_status,lapor_kategori,lapor_disposisi,lapor_klarifikasi,create_at,update_at,delete_at,user_id');
        $this->datatables->from('tbl_ppa_berita_acara');
        //add this line for join
        //$this->datatables->join('table2', 'tbl_ppa_berita_acara.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('kelola_berita_acara/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
            ".anchor(site_url('kelola_berita_acara/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
                ".anchor(site_url('kelola_berita_acara/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'berita_acara_id');
        return $this->datatables->generate();
    }

    //model
//    function hitung_biaya()
//    { 
//        $filter = " 1=1  ";
//            $data = $this->db->query(" 
//            SELECT SUM(A.biaya) AS total FROM (SELECT
//            rencana_aksi.id, 
//            rencana_aksi.skpd_id, 
//            rencana_aksi.kak_id, 
//            rencana_aksi.tahun, 
//            rencana_aksi.tujuan_pprg, 
//            rencana_aksi.biaya
//            FROM rencana_aksi) A WHERE  $filter AND A.tahun=".$_SESSION['Tahun_Anggaran']." GROUP BY A.tahun");
//
//    
//    return $data->row();
//        
//    }
    
//      function hitung_program()
//    { 
//     $filter = " 1=1  ";
//   $data = $this->db->query("SELECT COUNT(A.Kode_Program) as total_program  FROM (SELECT
//	tb_kak.Id_kak, 
//	tb_kak.Tahun_Anggaran, 
//	tb_kak.Kode_skpd, 
//	tb_kak.Kode_Program, 
//	tb_kak.Sasaran_Program, 
//	tb_kak.Program, 
//	tb_kak.Kegiatan FROM tb_kak ) A WHERE A.Tahun_Anggaran=".$_SESSION['Tahun_Anggaran']." GROUP BY A.Tahun_Anggaran ");
//    return $data->row();
//    }

}

/* End of file Model_kak.php */
/* Location: ./application/models/Model_kak.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-04-13 09:18:16 */
/* http://harviacode.com */