<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Ref_department_model extends CI_Model
{

    public $table = 'ref_department';
    public $id = 'id_department';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
//        $this->db->order_by($this->id, $this->order);
//        return $this->db->get($this->table)->result();
        $query = $this->db->query("SELECT
	ref_department.id_department,
	ref_department.`name`, 
	ref_department.leader, 
	ref_department.nip_leader, 
	ref_department.jabatan, 
	ref_department.address, 
	ref_department.phone, 
	ref_department.email, 
	ref_department.website, 
	tbl_user.id_users
FROM
	ref_department
	LEFT JOIN
	tbl_user
	ON 
		tbl_user.id_skpd = ref_department.id_department");
        
 if ($_SESSION['id_user_level'] == 2) {
       $query =  $this->db->where('ref_department.id_department', $_SESSION['id_skpd']);
        }
$row = $query->row_array();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_department', $q);
	$this->db->or_like('name', $q);
	$this->db->or_like('leader', $q);
        $this->db->or_like('jabatan', $q);
	$this->db->or_like('address', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('image', $q);
	$this->db->or_like('website', $q);
	$this->db->or_like('views', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('type', $q);
	$this->db->or_like('created_id', $q);
	$this->db->or_like('created_date', $q);
	$this->db->or_like('update_id', $q);
	$this->db->or_like('update_date', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_department', $q);
	$this->db->or_like('name', $q);
	$this->db->or_like('leader', $q);
	$this->db->or_like('address', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('image', $q);
	$this->db->or_like('website', $q);
	$this->db->or_like('views', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('type', $q);
	$this->db->or_like('created_id', $q);
	$this->db->or_like('created_date', $q);
	$this->db->or_like('update_id', $q);
	$this->db->or_like('update_date', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Ref_department_model.php */
/* Location: ./application/models/Ref_department_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-06-28 03:23:50 */
/* http://harviacode.com */