<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Ref_program_model extends CI_Model
{

    public $table = 'ref_program';
    public $id = 'id_sipd';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_sipd', $q);
	$this->db->or_like('id_urusan', $q);
	$this->db->or_like('kode_urusan', $q);
	$this->db->or_like('nama_urusan', $q);
	$this->db->or_like('id_bidang_urusan', $q);
	$this->db->or_like('kode_bidang_urusan', $q);
	$this->db->or_like('nama_bidang_urusan', $q);
	$this->db->or_like('id_program', $q);
	$this->db->or_like('kode_program', $q);
	$this->db->or_like('nama_program', $q);
	$this->db->or_like('id_giat', $q);
	$this->db->or_like('kode_giat', $q);
	$this->db->or_like('nama_giat', $q);
	$this->db->or_like('id_sub_giat', $q);
	$this->db->or_like('kode_sub_giat', $q);
	$this->db->or_like('nama_sub_giat', $q);
	$this->db->or_like('is_locked', $q);
	$this->db->or_like('vol_staf', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('action', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_sipd', $q);
	$this->db->or_like('id_urusan', $q);
	$this->db->or_like('kode_urusan', $q);
	$this->db->or_like('nama_urusan', $q);
	$this->db->or_like('id_bidang_urusan', $q);
	$this->db->or_like('kode_bidang_urusan', $q);
	$this->db->or_like('nama_bidang_urusan', $q);
	$this->db->or_like('id_program', $q);
	$this->db->or_like('kode_program', $q);
	$this->db->or_like('nama_program', $q);
	$this->db->or_like('id_giat', $q);
	$this->db->or_like('kode_giat', $q);
	$this->db->or_like('nama_giat', $q);
	$this->db->or_like('id_sub_giat', $q);
	$this->db->or_like('kode_sub_giat', $q);
	$this->db->or_like('nama_sub_giat', $q);
	$this->db->or_like('is_locked', $q);
	$this->db->or_like('vol_staf', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('action', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Ref_program_model.php */
/* Location: ./application/models/Ref_program_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-06-28 03:23:50 */
/* http://harviacode.com */