<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class User_model extends CI_Model
{

    public $table = 'user';
    public $id = 'id_user';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_user', $q);
	$this->db->or_like('create_time', $q);
	$this->db->or_like('update_time', $q);
	$this->db->or_like('visit_time', $q);
	$this->db->or_like('verified_time', $q);
	$this->db->or_like('code', $q);
	$this->db->or_like('fullname', $q);
	$this->db->or_like('gender', $q);
	$this->db->or_like('birth', $q);
	$this->db->or_like('phone', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('username', $q);
	$this->db->or_like('password', $q);
	$this->db->or_like('description', $q);
	$this->db->or_like('level', $q);
	$this->db->or_like('division', $q);
	$this->db->or_like('division_sub', $q);
	$this->db->or_like('image', $q);
	$this->db->or_like('ipaddress', $q);
	$this->db->or_like('active', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('token', $q);
	$this->db->or_like('province_id', $q);
	$this->db->or_like('regency_id', $q);
	$this->db->or_like('district_id', $q);
	$this->db->or_like('village_id', $q);
	$this->db->or_like('rt_id', $q);
	$this->db->or_like('rw_id', $q);
	$this->db->or_like('verified_email', $q);
	$this->db->or_like('google_id', $q);
	$this->db->or_like('google_image', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_user', $q);
	$this->db->or_like('create_time', $q);
	$this->db->or_like('update_time', $q);
	$this->db->or_like('visit_time', $q);
	$this->db->or_like('verified_time', $q);
	$this->db->or_like('code', $q);
	$this->db->or_like('fullname', $q);
	$this->db->or_like('gender', $q);
	$this->db->or_like('birth', $q);
	$this->db->or_like('phone', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('username', $q);
	$this->db->or_like('password', $q);
	$this->db->or_like('description', $q);
	$this->db->or_like('level', $q);
	$this->db->or_like('division', $q);
	$this->db->or_like('division_sub', $q);
	$this->db->or_like('image', $q);
	$this->db->or_like('ipaddress', $q);
	$this->db->or_like('active', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('token', $q);
	$this->db->or_like('province_id', $q);
	$this->db->or_like('regency_id', $q);
	$this->db->or_like('district_id', $q);
	$this->db->or_like('village_id', $q);
	$this->db->or_like('rt_id', $q);
	$this->db->or_like('rw_id', $q);
	$this->db->or_like('verified_email', $q);
	$this->db->or_like('google_id', $q);
	$this->db->or_like('google_image', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file User_model.php */
/* Location: ./application/models/User_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-06-28 03:23:50 */
/* http://harviacode.com */